config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships
  resources :beer_clubs do
    post 'toggle_confirm', on: :member
  end
  
  resources :users do
    post 'freeze_account', on: :member
  end
  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to: 'places#search'

  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'

 
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'

  get 'brewerylist', to: 'breweries#brewerylist'
  
  resources :ratings, only: [:index, :new, :create, :destroy]
 
  resource :session, only: [:new, :create, :delete]

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer_club

  validates_uniqueness_of :user_id, scope: :beer_club_id, message: "You are already a member"

	def to_s
		"#{self.name}, #{self.city}"
	end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
    @beer_clubs = BeerClub.all
    @user = current_user
  end

  # GET /memberships/new
  def new
    @beer_clubs = BeerClub.all
    @membership = Membership.new
    @user = current_user
    
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @beer_clubs = BeerClub.all
    @user = current_user
    @membership = Membership.new(membership_params)
    @membership.user_id = current_user.id
    @membership.confirm = false

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership.beer_club, notice: "#{@membership.user.username}, welcome to the club!" }
        format.json { render :show, status: :created, location: @membership }
      else
        @beer_clubs = BeerClub.all
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @beer_clubs = BeerClub.all
    @membership.destroy
    respond_to do |format|
      club = @beer_clubs.find_by id:@membership.beer_club_id
      format.html { redirect_to user_path(current_user), notice: 'Membership in ended.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:beer_club_id, :user_id, :confirm)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :beer_club_id %><br>
    <%= f.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :to_s) %>
  </div>
  <div class="actions">
    <%= f.submit %>
    
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Beer club</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.beer_club.name %></td>
        <td><%= membership.user_id %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership),class:'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path , class:'btn btn-primary'%>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beer club:</strong>
  <%= @membership.beer_club_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @membership.user_id %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>