config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships
  resources :beer_clubs do
    post 'toggle_confirm', on: :member
  end
  
  resources :users do
    post 'freeze_account', on: :member
  end
  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to: 'places#search'

  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'

 
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'

  get 'brewerylist', to: 'breweries#brewerylist'
  
  resources :ratings, only: [:index, :new, :create, :destroy]
 
  resource :session, only: [:new, :create, :delete]

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true,
                       length: { in: 3..15 }

  validates :password, length: { minimum: 4 }

  validates :password, format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{4,}\z/,  message: "has to contain one number and one upper case letter" }


  def self.most_active(n)
    sorted_by_rating_in_desc_order = User.all.select{ |u| u.ratings.any? }.sort_by{ |u| -(u.ratings.count) }
    sorted_by_rating_in_desc_order[0..(n-1)]
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_brewery
    return nil if ratings.empty?
    brewery_ratings = rated_breweries.inject([]) do |ratings, brewery|
      ratings << {
        name: brewery,
        rating: rating_of_brewery(brewery) }
    end

    brewery_ratings.sort_by { |brewery| brewery[:rating] }.reverse.first[:name]
  end

  def favorite_style
    return nil if ratings.empty?
    style_ratings = rated_styles.inject([]) do |ratings, style|
      ratings << {
        name: style,
        rating: rating_of_style(style) }
    end

    style_ratings.sort_by { |style| style[:rating] }.reverse.first[:name]
  end

  def rated_breweries
    ratings.map{ |r| r.beer.brewery }.uniq
  end

  def rated_styles
    ratings.map{ |r| r.beer.style }.uniq
  end

  def rating_of_brewery(brewery)
    ratings_of_brewery = ratings.select do |r|
      r.beer.brewery == brewery
    end
    ratings_of_brewery.map(&:score).sum / ratings_of_brewery.count
  end

  def rating_of_style(style)
    ratings_of_style = ratings.select do |r|
      r.beer.style == style
    end
    ratings_of_style.map(&:score).sum / ratings_of_style.count
  end

  def self.top(n)
    User.all.sort_by{ |u| -(u.ratings.count || 0) }.take(n)
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.admin = false
    @user.status = false
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      #only current user can modify itself
      if user_params[:username].nil? and @user == current_user and @user.update(user_params) and @user == current_user.admin
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    #only the current user can destroy itself
    if @user == current_user
      @user.destroy
      session[:user_id] = nil

      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { redirect_to user_path @user, notice: 'No rights to delete' }
    end
  end

  def freeze_account
    if  current_user.admin
      user = User.find(params[:id])
      user.update_attribute :status, (not user.status)
      user.save

      new_status = user.status? ? "frozen" : "reactive"
      redirect_to :back, notice:"User is now to #{new_status}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if @user.new_record? %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <% else %>
  <div class="field">
    New Password:<br />
    <%= f.password_field :password %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>


  <div class="actions">
    <%= f.submit class:'btn btn-default' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change Password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <% if current_user  and current_user.admin and user.status %>
          <td><span class="label label-info">account frozen</span></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if not current_user.nil? %>
  <%= link_to 'New User', new_user_path, class:'btn btn-default' %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @user.username %>
<% if @user.status %> <span class="label label-danger">account frozen</span> <% end%>
</h2>


<!-- List membership -->
<p>
	<% if @user.memberships.empty? %>
		has no memberships
	
	<% else %>
	<%= "member of" %>
			<% @user.beer_clubs.each do |beer_club| %>
			<%= link_to beer_club.to_s, beer_club_path(beer_club) %> 
			<% end %>
		
	</ul>
	<% end %>
</p>

<!-- List Ratings-->	
<p>
	<% if @user.ratings.empty? %>
		has made no ratings
	<% else %>
	<%= "has made #{pluralize(@user.ratings.count,'ratings')}, average #{@user.average_rating}" %>
	<h2>Ratings </h2>
	<ul>
		<% @user.ratings.each do |rating| %>
			<li> <%= rating.to_s %>
				<% if @user == current_user %>
	 				<%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
	 			<% end %>
			</li>
		<% end %>
	</ul>
	<% end %>
</p>	

<p>
	<strong>Favorite style: </strong>
	<%= @user.favorite_style %>
</p>
<% if false %>
<p>
	<strong>Favorite brewery: </strong>

	<%= link_to "#{@user.favorite_brewery.name}", @user.favorite_brewery %>
</p>
<% end %>

<% if @user == current_user %>
	<td><%= link_to 'Edit', edit_user_path(@user) ,class:'btn btn-primary' %></td>
	<td><%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } ,class:'btn btn-danger' %></td>

	<% elsif current_user.admin %>
		<%= link_to "Freeze account", freeze_account_user_path(@user.id), method: :post, class: "btn btn-info" %>
<% end %>
</p>