config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships
  resources :beer_clubs do
    post 'toggle_confirm', on: :member
  end
  
  resources :users do
    post 'freeze_account', on: :member
  end
  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to: 'places#search'

  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'

 
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'

  get 'brewerylist', to: 'breweries#brewerylist'
  
  resources :ratings, only: [:index, :new, :create, :destroy]
 
  resource :session, only: [:new, :create, :delete]

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
	has_many :beers, dependent: :destroy
	has_many :ratings, through: :beers
	
	include RatingAverage	
	validates :name, presence: true, allow_blank: false
	validates :year, numericality: {only_integer: true, greater_than_or_equal_to: 1042}
	validate :year_current

	scope:active, -> { where active:true }
	scope:retired, -> { where active:[nil,false] }

	
	def year_current
		if year > Time.now.year
			errors.add(:year, "Year cannot be Future ")
		end
	end
  
  def self.top(n)
    Brewery.all.sort_by{ |b| -(b.average_rating || 0) }.take(n)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_admin, except: [:index, :show, :brewerylist]

  def brewerylist
  end

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired

    order = params[:order] || 'name'

    if(session[:dir].nil?)
      session[:dir] = 'asc'  #default asc year
    end

    if(session[:dir] == 'asc')
      @active_breweries = case order
        when 'name' then @active_breweries.sort_by{ |b| b.name}
        when 'year' then @active_breweries.sort_by{ |b| b.year}
      end

      @retired_breweries = case order
        when 'name' then @retired_breweries.sort_by{ |b| b.name}
        when 'year' then @retired_breweries.sort_by{ |b| b.year}
      end

      session[:dir] = 'desc'

    else
      if(session[:order] == order)
        @active_breweries = @active_breweries.reverse
        @retired_breweries = @retired_breweries.reverse

        session[:dir] = 'asc'
      end
    end

    session[:order] = order
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_fragment('brewerylist')
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_fragment('brewerylist')
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire_fragment('brewerylist')
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

    def authenticate
        admin_accounts = { "admin" => "secret", "pekka" => "beer", "arto" => "foobar", "matti" => "ittam"}
	authenticate_or_request_with_http_basic do |username, password|
	admin_accounts.each do |user, passwd|
		return true if user == username and passwd == password
	end
	end
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<% cache "brewerylist", skip_digest: true do %>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= link_to 'Name', breweries_path(order:'name') %></th>
      <th><%= link_to 'Year', breweries_path(order:'year') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
          <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/breweries/brewerylist.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.13/angular.min.js"></script>
<script>
    var myApp = angular.module('myApp', []);

    myApp.controller("BreweriesController", function ($scope, $http) {
        $http.get('breweries.json').success( function(data, status, headers, config) {
            $scope.breweries = data;
        });

        $scope.order = 'name';

        $scope.sort_by = function (order){
            $scope.order = order;
            console.log(order);
        }

        $scope.searchText = '';
    });
</script>

<h2>Breweries</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

  search:  <input ng-model="searchText">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="sort_by('name')">name</a> </th>
    <th> <a ng-click="sort_by('year')">year</a> </th>
    </thead>
    <tr ng-repeat="brewery in breweries| orderBy:order | filter:searchText">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
    </tr>
  </table>

</div>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breweries </h1>
<p>Number of breweries: <%= @breweries.count %></p>
<h2>Active</h2>
<p> Number of active breweries: <%= @active_breweries.count %> </p>
<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<%= render 'list', breweries: @retired_breweries %>

<br>
<% if not current_user.nil? %>
  <%= link_to 'New Brewery', new_brewery_path, class:'btn btn-primary' %>
<% end %>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/panimot.html.erb
panimot <%= @breweries.count %>

app/views/breweries/show.html.erb
<% cache @brewery do %>

<h2><%= @brewery.name %>
  <% if not @brewery.active  %>
      <span class="label label-info">retired</span>
  <% end %>
</h2>

<p>
  <em>Established in </em>
  <%= @brewery.year %>
</p>

<p>Number of beers <%= @brewery.beers.count%> </p>

<ul>
 <% @brewery.beers.each do |beer| %>
   <li><%= link_to beer.name, beer %></li>
 <% end %>
</ul>

<% if @brewery.ratings.empty? %>
    <p>beers of the brewery have not yet been rated! </p>
<% else %>
    <p>Has <%= pluralize(@brewery.ratings.count,'rating') %>, average <%= @brewery.average_rating %> </p>
<% end %>
<% end %>
<% if current_user %>
  <%= link_to 'Edit', edit_brewery_path(@brewery), class:"btn btn-primary"  %>
  <%= link_to 'Destroy', @brewery, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"  %>
  <%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
<% end %>